### ISSUE TITLE
has_many associations

### ISSUE THREAD

**Issue by aaronchi** [flyerhzm/simple_cacheable#1]
Any plans to support has_many associations?

It would have to clear the cache if one of the child values was updated

**Comment by flyerhzm** [comment]
has_many and has_one associations have been supported from 1.1.0 version

**Comment by aaronchi** [comment]
Thanks!

This is not working 100% though. The cache method for has_many needs to call `#{association_name}.all` so it caches the actual results and not an ActiveRecord::Relation object

**Comment by flyerhzm** [comment]
1.1.1 already released to fix this issue, thanks for your patch.
