### ISSUE TITLE
这种场景不知道 cache 是否能自动清理

### ISSUE THREAD

**Issue by huacnlee** [flyerhzm/simple_cacheable#19]
User, Post

``` rb
class Post
  belongs_to :user
  model_cache do
    with_key
    with_association :user
  end
end
```

View:

``` erb
<%= post.cached_user %>
```

当用户头像更改的时候，上面 View 处引用的 cached_user 的缓存会自动清理掉么？
我的项目场景里面发现没有

**Comment by flyerhzm** [comment]
这个应该被自动清理掉，你可以看看 cached_user 读的 memcached key 是不是 users/xxx

**Comment by huacnlee** [comment]
应该是其他几个三方库引出的问题，看到 log 里面有一段：

```
undefined method `expire_association_cache' for nil:NilClass
```

我这个 model 里面用到的三方库有:

``` ruby
class Post
  include Redis::Objects
  include RailsSettings::Extend 
  acts_as_taggable
  acts_as_taggable_on :feature
  acts_as_nested_set # awesome_nested_set
end
```

待我来查查问题原因

**Comment by huacnlee** [comment]
找到 `expire_association_cache` 处的代码，打印出来看，发现似乎上面的 `expire_association_cache` 个和这个问题没有关系

**Comment by huacnlee** [comment]
Memcached 的 key 是这样的，`foo:users/2561737`

修改 User 的过程，没有看到有出现清除 `foo:users/2561737` 的日志，应该是 callback 方法没有被掉用到

**Comment by huacnlee** [comment]
找到问题根源了，awesome_nested_set 引出的问题...

Before:

``` ruby
class Post
  include Cacheble 
  awesome_nested_set
  model_cache do
    with_key
    with_association :children, :parent
  end
end
```

如果我把 `model_cache` 方法写到 `awesome_nested_set` 的后面，那 `with_key` 里面定义的 [after_commit 动作](https://github.com/flyerhzm/simple_cacheable/blob/0c620bc5ba57d6c9594a2652c8795605e35aea5f/lib/cacheable.rb#L20) 就无法生效。

解决方法就是将 `with_key` 提到 `awesome_nested_set` 之前去：

``` ruby
class Post
  include Cacheble 

  model_cache do
    with_key
    with_association :categroy
  end

  acts_as_nested_set
  # 这里 acts_as_nested_set 的 parent, children 就没法搞 cache 了
  # 我有尝试在 acts_as_nested_set 后面再加上 
  # model_cache do
  #   with_association :children, :parent
  # end
  # 这样也会引出同样的 Bug，所以暂时去掉了，回头看看 acts_as_nested_set 的问题在哪里，之前把 acts-as-taggable-on 的功能也是这么覆盖了。
end
```

**Comment by huacnlee** [comment]
题外话

为什么 cache_key 只用 model 名字 + id ，而不用上 updated_at 字段呢
比如 users/12/1358178515 这样每当数据更新的时候,updated_at 自动变化，cache key 也变了，cache 自然就过期了，都不需要手动删除

**Comment by flyerhzm** [comment]
因为执行 User.find_cached 的时候只知道id，不知道updated_at，就没有办法查找cache啦

**Comment by huacnlee** [comment]
明白了
