### ISSUE TITLE
Getting Collections

### ISSUE THREAD

**Issue by ScotterC** [flyerhzm/simple_cacheable#9]
Oddly enough I was building out this same functionality when I found this great gem so I'm happy to contribute to it and join forces.

One thing I'd like to discuss is the caching of collection requests.

@tobi had this [awesome presentation](http://www.infoq.com/presentations/lutke-rockstar-memcaching) a few years back on the right and wrong way to do it.

The wrong way but never hits the db:

```
  def self.find_cached_where(conditions = nil)
    Rails.cache.fetch("#{self.model_name.tableize}/#{conditions.to_param}") do
      self.where(conditions)
    end
  end
```

The problem with this as he points out in the presentation is that if something gets deleted or changed within the collection it won't update this collection cache.

The right way but hits the db:

```
  def self.find_cached_where(conditions = nil)
    self.where(conditions).pluck(:id).map do |id|
      find_cached(id)
    end
  end
```

This gets the appropriate ids to request and then hits the cache to actually request them.  Always correctly up to date but you need to hit the db for the ids.  I'm happy to make a pull request to add this functionality but I'd like to hear anyone's thoughts on how much speed advantage there is on hitting the database for ids vs pulling full rows out.

**Comment by flyerhzm** [comment]
@ScotterC I don't think it's a good idea to cached where result.
1. considering arel syntax, developers always add additional order, limit and other conditions, like it only needs to query 10 items with .where(xxx).limit(10), while your cache method will cache all items.
2. touching memcached multiple times is also a time-consumer task, sometimes a single sql query is faster than calling multiple times to memcached.

I think it would be better to leave the multiple items caching to developers, I prefer the following way in some situations

``` ruby
item_ids = Rails.cache.read("blah_blah_ids")
items = Item.where(:id => item_ids)
```

What do you think?

**Comment by ScotterC** [comment]
I think it's kind of an interesting tug of war between wanting to offer easy conventions but it's a situation that you need to be aware of what you're doing because it can become a real gotcha to a developer.

I guess the existing method caching can be used for a collection of some sort and will satisfy my requirement for now.

Could possibly be used for scopes too.  One thing that might be fun to try is caching a method with it's arguments.

We're using the expire_model_cache method for anything specific?  I forgot to add the expire_all_attribute_cache to it.

**Comment by flyerhzm** [comment]
expiring cache is one of the most difficult things, developers must be aware what are cached, the gem should help for some common and simple cases, but if it can't promise correctness, it should do less.

**Comment by ScotterC** [comment]
Cool.  Let's leave it how it is because I can't think of a way to give that sort of promise.
